name: Vale

# Run this job whenever a Markdown file is changed in a feature branch
on:
  push:
    branches:
      - '!main'
    paths:
      - '**.md'

jobs:
  Vale:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Lint documentation
        uses: errata-ai/vale-action@reviewdog
        with:
          # Report results for every PR and push
          reporter: github-check
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/a
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}